DATASET:
  NAME: ILSVRC2012
  NUM_CLASSES: 1000
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.05
  WEIGHT_DECAY: 1e-4
  TRAIN_BATCH_SIZE: 128
  WARMUP: True
  WARMUP_EPOCH: 5
  WARMUP_FACTOR: 0.2
ISON:
  DEPTH: 18
  ORTHO_COEFF: 1e-4
  HAS_BN: False
  HAS_ST: True
  SReLU: True
  DIRAC_INIT: True
  HAS_RES_MULTIPLIER: True
  RES_MULTIPLIER: 0.0
  DROPOUT: True
  DROPOUT_RATE: 0.4
